name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
              # pull files
              cd ~/deploy/build
              git pull
              cd frontend
              npm install
              npm run build

              # build and serve frontend
              cd ~/deploy/build/frontend
              npm install
              npm run build
              rm -rf /var/www/junozhang.com/*
              cp -r dist/* /var/www/junozhang.com/
              chmod -R 755 /var/www/junozhang.com

              # refresh express server (move pm2 process onto deployer)

              pm2 restart express
              pm2 restart dbot
              
              echo 'Deployment to junozhang.com finished'
