name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: | 
            # clone the repo into /tmp
            rm -rf /tmp
            git clone git@github.com:juuunoz/juuunoz.github.io /tmp

             # create the build and put it in the right place for nginx to serve
            cd /tmp/frontend
            
            npm install
            npm run build

            rm -rf /var/www/junozhang.com/*
            cp -r dist/* /var/www/junozhang.com/

            chmod -R 755 /var/www/junozhang.com

            rm -rf /tmp/frontend

            echo 'Deployment to junozhang.com finished'
